### ISSUE TITLE
brilliant idea: support the non javascript guys

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-javascript#20]
Here a possibly brilliant idea for supporting the non javascript guys. HOWEVER, IT IS OF IMMEDIATE BENEFIT FOR YOU..... for RAPID DEVELOPMENT

let us assume I have a cms command that returns a son object similar to our Printer

lets  use the "cms flavor list command"

What if we coudl do the following 

cms viewer add --name="my command" --icon="incon.jpg" --command="! cms set cloud=chameleon; cms flavor list command"

or assuming that cms is installed and we use Joshes brilliant way to invoke

cms viewer add --name="my command" --icon="incon.jpg" --command="set cloud=chameleon\n flavor list --refresh --output=flat"

This thing would add on the left hand side a link with icon (icon options) that then executes the script. It simply appands

or in yaml:

```
sidebar:
   mycommand:
       label: My Command
        icon: icon.png or icon name form icon set or something like that (optional)
       execute: |-
           set cloud=chameleon
           flavor list --refresh --output=flat
     renderer:
     - table
     - card
     columns: (possibly optional, but we could make mandatory)
        order: 
        - name
        - size
        header:
        - Name
        - Size
```

Would that not solve all the issues you have with quickly adding new features in the sidebar

Now if you think about this this could even be applied to the topbar, where we could add icons and other things

So this would immediately be useful, as we can also remove things fore people that do not like vms but containers, and we just provide container functions from cloudmesh
